# Usar uma imagem do Python
FROM python:3.9

# Definir o diretório de trabalho dentro do container
WORKDIR /Server/

# Copiar os arquivos do servidor para dentro do container

# Expor a porta que o servidor usa
EXPOSE 8000

# Comando para rodar o servidor
CMD ["python", "Server.py"]
